export default {
  pieces: [
    {
      name: 'Weather',
      you: 'It looks like it might rain.',
      robert: 'Yeah, I guess.',
      melinda: 'It does look cloudy.',
      monster: 0,
    },
    {
      name: 'Bench',
      you: 'This is a wooden bench.',
      robert: 'Don\'t forget it\'s brown too.',
      melinda: 'I guess I\'m glad you\'re not blind',
      monster: 0,
    },
    {
      name: 'Nickname',
      you: 'Some people call me the Space Cowboy.',
      robert: 'What about the gangster or love?',
      melinda: 'Yeah, ok Maurice.',
      monster: 0,
    },
    {
      name: 'Apple',
      you: 'Android or Apple?',
      robert: 'Do you think I\'m made of money?',
      melinda: 'No.',
      monster: 1,
      background: 'bad',
    },
    {
      name: 'Stamps',
      you: 'I love collecting stamps.',
      robert: 'Didn\'t know we lived in the 1960\'s.',
      melinda: 'Makes sense, not sure anyone wants a letter from you.',
      monster: 2,
      background: 'bad',
    },
    {
      name: 'Top Gun',
      you: 'Talk to me Goose.',
      robert: 'Hated that movie, Hated Tom Cruise - you can see where this is going.',
      melinda: 'Is that from Star Trek or something?',
      monster: 2,
      background: 'bad',
    },
    {
      name: 'Picture',
      you: 'I only take pictures from this side, it\'s my good side',
      robert: 'I\'m not taking your picture',
      melinda: 'Ok Narcissus',
      monster: 2,
      background: 'bad',
    },
    {
      name: 'Signs',
      you: 'I\'m a capricorn!',
      robert: 'Glad we\'re incompatible',
      melinda: 'This explains a lot.',
      monster: 3,
      background: 'bad',
    },
    {
      name: 'Wow',
      you: 'Ever play World of Warcraft?',
      robert: '....',
      melinda: '....',
      monster: 4,
      background: 'bad',
    },
    {
      name: 'Mother',
      you: 'Sorry, my mother couldn\'t make it.',
      robert: 'I\'m not that scary..',
      melinda: 'You\'re kidding? Right?',
      monster: 10,
      background: 'bad',
    },
    {
      name: 'Hair',
      you: 'I like your hair - it is very poofy',
      robert: 'Couldn\'t find anything else to compliment huh?',
      melinda: '.....',
      monster: 5,
      background: 'bad',
    },
    {
      name: 'Zit',
      you: 'I\'m not conceited - but if I have a zit I will call in sick to work',
      robert: 'Took a sick day today then?',
      melinda: 'Concealer won\'t hide that..',
      monster: 7,
      background: 'bad',
    },
    {
      name: 'Trains',
      you: 'I love collecting miniature trains.',
      robert: 'Like Thomas the Tank Engine? Cool.',
      melinda: 'That must take a lot of dedication, good on you!',
      monster: -1,
      background: 'good',
    },
    {
      name: 'Exercise',
      you: 'I"m training for a marathon.',
      robert: 'That\'s cool - I\'ve heard of running before.',
      melinda: 'Staying in shape is always worth it.',
      monster: -1,
      background: 'good',
    },
    {
      name: 'Charity',
      you: 'Do you do volunteer work?',
      robert: 'I help struggling game developers learn how to communicate.',
      melinda: 'I re-home cats. From my house, to somewhere else.',
      monster: -2,
      background: 'good',
    },
    {
      name: 'Music',
      you: 'Want a copy of my mix tape?',
      robert: 'Sure - always looking for new stuff',
      melinda: 'As long as it\'s rap and pays homage to veganism, firefly, or Tibet',
      monster: -2,
      background: 'good',
    },
    {
      name: '강아지',
      you: '나는 강아지를 좋아한다.',
      robert: 'Woof.',
      melinda: 'Woof.',
      monster: -1,
      background: 'good',
    },
    {
      name: 'Nervous',
      you: 'I am a little nervous, sorry.',
      robert: 'No worries, I am too.',
      melinda: 'First dates are a little nerve wracking for sure',
      monster: -3,
      background: 'good',
    },
    {
      name: 'Eyes',
      you: 'You have very kind eyes',
      robert: 'Thank you, kind of you to notice',
      melinda: 'They are windows to the soul',
      monster: -4,
      background: 'good',
    },
    {
      name: 'Geese',
      you: 'I hate geese',
      robert: 'Agreed. They should be banned.',
      melinda: 'Geese are disgusting and literally the worst of all fowl.',
      monster: -10,
      background: 'good',
    },
  ],
};
