export default {
  pieces: [
    {
      name: 'Weather',
      you: 'It looks like it might rain.',
      robert: 'Yeah, I guess',
      melinda: 'It does look cloudy',
      monster: 0,
    },
    {
      name: 'Bench',
      you: 'This is a wooden bench.',
      robert: 'Don\'t forget it\'s brown too',
      melinda: 'I guess I\'m glad you\'re not blind',
      monster: 0,
    },
    {
      name: 'Nickname',
      you: 'Some people call me the Space Cowboy.',
      robert: 'What about the gangster or love?',
      melinda: 'Yeah, ok Maurice',
      monster: 0,
    },
    {
      name: 'Stamps',
      you: 'I love collecting stamps.',
      robert: 'Didn\'t know we lived in the 1960\'s',
      melinda: 'Makes sense, not sure anyone wants a letter from you',
      monster: 2,
      background: 'bad',
    },
    {
      name: 'Top Gun',
      you: 'Talk to me Goose',
      robert: 'Hated that movie, Hated Tom Cruise - you can see where this is going',
      melinda: 'Geese are disgusting and literally the worst of all fowl',
      monster: 2,
      background: 'bad',
    },
    {
      name: 'Picture',
      you: 'I only take pictures from this side, it\'s my good side',
      robert: 'I\'m not taking your picture',
      melinda: 'Ok Narcissus',
      monster: 2,
      background: 'bad',
    },
    {
      name: 'Signs',
      you: 'I\'m a capricorn!',
      robert: 'Glad we\'re incompatible',
      melinda: 'This explains a lot.',
      monster: 3,
      background: 'bad',
    },
    {
      name: 'Mother',
      you: 'Sorry, my mother couldn\'t make it.',
      robert: 'I\'m not that scary..',
      melinda: 'You\'re kidding? Right?',
      monster: 5,
      background: 'bad',
    },
    {
      name: 'Hair',
      you: 'I like your hair - it is very poofy',
      robert: 'Couldn\'t find anything else to compliment huh?',
      melinda: '.....',
      monster: 5,
      background: 'bad',
    },
    {
      name: 'Zit',
      you: 'I\'m not conceited - but if I have a zit I will call in sick to work',
      robert: 'Took a sick day today then?',
      melinda: 'Not sure concealer would hide that..',
      monster: 5,
      background: 'bad',
    },
    {
      name: 'Trains',
      you: 'I love collecting miniature trains.',
      robert: 'Like Thomas the Tank Engine? Cool.',
      melinda: 'That must take a lot of dedication, good on you!',
      monster: -1,
      background: 'good',
    },
    {
      name: 'Nervous',
      you: 'I am a little nervous, sorry.',
      robert: 'No worries, I am too.',
      melinda: 'First dates are a little nerve wracking for sure',
      monster: -2,
      background: 'good',
    },
  ],
};
